---
#title: "Información sobre el curso"
toc: true
#self-contained: true
---

## Información sobre el curso

::: {.callout-note appearance="minimal" icon="false"}
## 

-   Forma parte de la oferta del [SFPIE](https://www.uv.es/sfpie){target="_blank"} de la Universitat de València. La ficha oficial del curso está [aquí](https://www.uv.es/uvweb/servei-formacio-permanent-innovacio-educativa/ca/oferta-formativa/introduccio-r-1286213964422/PDIFormacio.html?id=1286361653595){target="_blank"}.


-   En el curso usaremos 3 programas. Principalmente usaremos [R](https://cran.r-project.org/){target="_blank"} a través de [RStudio](https://www.rstudio.com/products/rstudio/download/#download){target="_blank"}. En una de las últimas sesiones del curso también usaremos [Quarto](https://quarto.org/).


-   Se recomienda tener instaladas **versiones recientes** de los 3 programas. Tienes instrucciones de instalación más abajo

-   Es muy-muy conveniente, acudir al curso con tu **propio ordenador**. Además, es conveniente que traigas **un ratón**: piensa que buena parte de los errores que cometeremos se deberán a la precisión en copy-paste. Evitémoslo!!

-   Los materiales que usaremos están en [Materiales](materiales.qmd).
:::


## Horario y aula

::: {.callout-note appearance="minimal" icon="false"}
## 

| Día                      | Hora          | Lugar                             | Profesor     |
|--------------------------|---------------|-----------------------------------|--------------|
| 22 de abril (lunes)      | 16:00 a 20:00 | Aula 0.2 SFPIE (Campus Tarongers) | Vicente      |
| 23 de abril (martes)     | 16:00 a 20:00 | Aula 0.2 SFPIE (Campus Tarongers) | Pedro        |
| 24 de abril (miércoles)  | 16:00 a 20:00 | Aula 0.2 SFPIE (Campus Tarongers) | Pedro        |
| 29 de abril (lunes)      | 16:00 a 20:00 | Aula 0.2 SFPIE (Campus Tarongers) | Vicente      |
| 30 de abril (martes)     | 16:00 a 20:00 | Aula 0.2 SFPIE (Campus Tarongers) | Vicente      |
| 6  de mayo (lunes)       | 16:00 a 20:00 | Aula 0.2 SFPIE (Campus Tarongers) | Pedro        |
| 7  de mayo (martes)      | 16:00 a 19:00 | Aula 0.2 SFPIE (Campus Tarongers) | Pedro        |
| 8  de mayo (miércoles)   | 16:00 a 19:00 | Aula 0.2 SFPIE (Campus Tarongers) | Vicente      |



<br>

Las clases se desarrollarán en el **Campus de Tarongers**, concretamente en el **aula 0.2 del SFPIE** (Servicio de Formación Permanente e Innovación Educativa) de la Universitat de València. 

El SFPIE está en el edificio "Centro de Formación y Calidad Manuel Sanchis Guarner" que está en la C/ Serpis, 29, 46022 València. Tienes un **mapa** de Google [aquí](https://www.google.es/maps/place/Centro+de+Formaci%C3%B3n+y+Calidad+Manuel+Sanchis+Guarner/@39.4750955,-0.346133,17z/data=!3m1!4b1!4m6!3m5!1s0xd6049dbfd241e75:0xc257e3f91a60e197!8m2!3d39.4750914!4d-0.3435581!16s%2Fg%2F11r_fpk8ms?hl=es&entry=ttu){target="_blank"}, y [aquí](https://www.uv.es/uvweb/centro-formacion-calidad-manuel-sanchis-guarner/es/centro-formacion-calidad-sanchis-guarner-1285909558032.html){target="_blank"} la web del centro.
:::

<br>

## Programas (instalación)

::: {.callout-important collapse="false" appearance="default" icon="false"}
## Instalación de R, RStudio y Quarto

-   En el curso usaremos 3 programas: R, RStudio y Quarto, así que tenemos que instalarlos

-   Has de instalar los programas en este orden:

    1.  R: <https://cran.r-project.org/>{target="_blank"}

    2.  RStudio: <https://posit.co/download/rstudio-desktop/>{target="_blank"}
    
    3. Quarto: <https://quarto.org/docs/download/>{target="_blank"}

-   Para ello, solamente has de descargar las versiones de los instaladores adecuadas para tu sistema operativo
:::

<br>



::: {.callout-important collapse="true" appearance="default" icon="false"}
## Instalación de paquetes

-   En el curso también usaremos algunos paquetes de R, así que hay que instalarlos

- Los paquetes se han de instalar una vez hayas instalado los 3 programas (R, RStudio y Quarto)

- Los paquetes no son necesarios para el primer día del curso, así que los instalaremos en clase durante la **segunda sesión** del curso
  
:::




::: {.callout-important collapse="true" appearance="default" icon="false"}
## ¿Cómo instalar los paquetes?

- Recuerda que Los paquetes no son necesarios para el primer día del curso, así que los instalaremos en clase durante la segunda sesión

- Algunos paquetes se han de compilar por lo que hay que tener las herramientas necesarias, así que:

    - Si usas Windows instalaremos **Rtools**. [Aquí](https://cran.r-project.org/bin/windows/Rtools/) puedes descargarte el instalador adecuado
    
    - Si tienes un Mac, tendrás que instalar the **Xcode Command Line Tools**. Lo normal es que lo tengas ya instalado, si no fuese el caso, [aquí](https://www.makeuseof.com/install-xcode-command-line-tools/) te explican como hacerlo. Además, como nos cuentan [aquí](https://psyteachr.github.io/msc-data-skills/installingr.html), si tienes un Mac, es conveniente instalar **XQuartz**, para ello sólo tienes que buscar el instalador en <https://www.xquartz.org/>

  
- Finalmente, para instalar los paquetes que usaremos durante el curso tendremos que **ejecutar las siguientes instrucciones**:

```{r}
#| eval: false
#| code-line-numbers: false
#| code-overflow: wrap
#| code-fold: true
#| code-summary: "Código para instalar los paquetes"

#- instalación de paquetes ---------------------------------

install.packages("pak")

mys_pkgs <- c("tidyverse", "curl", "eurostat", "here", "palmerpenguins", "quantmod", "rio", "gt", "DT", "gapminder", "markdown")
pak::pkg_install(mys_pkgs)   

mys_pkgs <- c("usethis", "janitor", "ggthemes", "gganimate", "perezp44/pjpv.curso.R.2022", "sjPlot")
pak::pkg_install(mys_pkgs)   

mys_pkgs <- c("sf", "rcartocolor", "rmapshaper", "gtExtras", "patchwork", "magick")
pak::pkg_install(mys_pkgs)   

mys_pkgs <- c("kableExtra", "modelsummary", "rpivotTable", "widyr", "irlba", "tmap")
pak::pkg_install(mys_pkgs)

mys_pkgs <- c("GGally", "ggtext", "Financial-Times/ftplottools", "maps")
pak::pkg_install(mys_pkgs)  

mys_pkgs <- c("summarytools", "glin/reactable", "agstn/dataxray", "naniar")
pak::pkg_install(mys_pkgs)  

mys_pkgs <- c("DataExplorer", "corrr", "inspectdf", "explore", "stargazer", "apaTables")
pak::pkg_install(mys_pkgs)   

mys_pkgs <- c("easystats", "plotly")
pak::pkg_install(mys_pkgs)

#- finalmente, si te instalas todos los paquetes, se instalarán 284 pkg's aprox. (q ocupan 842 MB aprox.)
pkgs <- pak::pkg_list()

#- normalmente tendrás 2 librerías
.libPaths()
#- en la primera tienes los pkgs de "R-base": "C:/Program Files/R/R-4.3.0/library"   
#- en la segunda tienes los paquetes q se instala un usuario:  "C:/Users/Usuario/AppData/Local/R/win-library/4.3" 


#- más cosas ---------------------------------------
# usethis::edit_rstudio_prefs()
# usethis::use_blank_slate() 

# quarto install tool tinytext
# quarto install tinytex --update-path
# quarto install tool chromium
```

:::
